# Generated by Django 5.0.2 on 2025-09-30 17:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrepreneurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du template')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('financial', 'Financier'), ('operational', 'Opérationnel'), ('performance', 'Performance'), ('compliance', 'Conformité'), ('custom', 'Personnalisé')], max_length=20, verbose_name='Catégorie')),
                ('is_system', models.BooleanField(default=False, verbose_name='Template système')),
                ('template_config', models.JSONField(default=dict, verbose_name='Configuration du template')),
                ('sections', models.JSONField(default=list, verbose_name='Sections du rapport')),
                ('charts_config', models.JSONField(default=list, verbose_name='Configuration des graphiques')),
                ('default_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], default='pdf', max_length=10, verbose_name='Format par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Template actif')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Template de rapport',
                'verbose_name_plural': 'Templates de rapports',
                'db_table': 'report_templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre du rapport')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('report_type', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('annual', 'Annuel'), ('custom', 'Personnalisé')], max_length=20, verbose_name='Type de rapport')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], default='pdf', max_length=10, verbose_name='Format')),
                ('period_start', models.DateField(verbose_name='Début de période')),
                ('period_end', models.DateField(verbose_name='Fin de période')),
                ('data', models.JSONField(verbose_name='Données du rapport')),
                ('template_config', models.JSONField(default=dict, verbose_name='Configuration du template')),
                ('is_generated', models.BooleanField(default=False, verbose_name='Rapport généré')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Chemin du fichier')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille du fichier (bytes)')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de génération')),
                ('generation_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée de génération (secondes)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='entrepreneurs.activity', verbose_name='Activité')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur cible')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Notification push'), ('download', 'Téléchargement')], max_length=20, verbose_name='Méthode de livraison')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('delivered', 'Livré'), ('failed', 'Échec'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Nombre de tentatives')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Nombre max de tentatives')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_distributions', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='reports.report', verbose_name='Rapport')),
            ],
            options={
                'verbose_name': 'Distribution de rapport',
                'verbose_name_plural': 'Distributions de rapports',
                'db_table': 'report_distributions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la planification')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('frequency', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('annual', 'Annuel')], max_length=20, verbose_name='Fréquence')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('generation_time', models.TimeField(verbose_name='Heure de génération')),
                ('auto_send', models.BooleanField(default=False, verbose_name='Envoi automatique')),
                ('recipients', models.JSONField(default=list, verbose_name='Destinataires')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('paused', 'En pause'), ('cancelled', 'Annulé')], default='active', max_length=20, verbose_name='Statut')),
                ('last_generated', models.DateTimeField(blank=True, null=True, verbose_name='Dernière génération')),
                ('next_generation', models.DateTimeField(blank=True, null=True, verbose_name='Prochaine génération')),
                ('total_generated', models.PositiveIntegerField(default=0, verbose_name='Total généré')),
                ('success_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux de réussite (%)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur cible')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reporttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Planification de rapport',
                'verbose_name_plural': 'Planifications de rapports',
                'db_table': 'report_schedules',
                'ordering': ['-created_at'],
            },
        ),
    ]
