# Generated by Django 5.0.2 on 2025-09-30 17:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrepreneurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre du rapport')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('report_type', models.CharField(choices=[('performance', 'Performance'), ('trends', 'Tendances'), ('comparison', 'Comparaison'), ('forecast', 'Prévisions'), ('impact', 'Impact')], max_length=20, verbose_name='Type de rapport')),
                ('target_audience', models.CharField(choices=[('entrepreneur', 'Entrepreneur'), ('coach', 'Coach'), ('bailleur', 'Bailleur'), ('admin', 'Administrateur')], max_length=20, verbose_name='Public cible')),
                ('data_config', models.JSONField(default=dict, verbose_name='Configuration des données')),
                ('visualizations', models.JSONField(default=list, verbose_name='Visualisations')),
                ('insights', models.JSONField(default=list, verbose_name='Insights générés')),
                ('period_start', models.DateField(verbose_name='Début de période')),
                ('period_end', models.DateField(verbose_name='Fin de période')),
                ('is_generated', models.BooleanField(default=False, verbose_name='Rapport généré')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de génération')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': "Rapport d'analyse",
                'verbose_name_plural': "Rapports d'analyse",
                'db_table': 'analytics_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KPIMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du KPI')),
                ('description', models.TextField(verbose_name='Description')),
                ('metric_type', models.CharField(choices=[('financial', 'Financier'), ('operational', 'Opérationnel'), ('growth', 'Croissance'), ('efficiency', 'Efficacité'), ('sustainability', 'Durabilité'), ('impact', 'Impact social')], max_length=20, verbose_name='Type de métrique')),
                ('calculation_type', models.CharField(choices=[('sum', 'Somme'), ('average', 'Moyenne'), ('percentage', 'Pourcentage'), ('ratio', 'Ratio'), ('count', 'Comptage'), ('custom', 'Calcul personnalisé')], max_length=20, verbose_name='Type de calcul')),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valeur cible')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Unité de mesure')),
                ('formula', models.TextField(blank=True, verbose_name='Formule de calcul')),
                ('warning_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Seuil d'avertissement")),
                ('critical_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Seuil critique')),
                ('is_active', models.BooleanField(default=True, verbose_name='KPI actif')),
                ('is_system', models.BooleanField(default=False, verbose_name='KPI système')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Métrique KPI',
                'verbose_name_plural': 'Métriques KPI',
                'db_table': 'kpi_metrics',
                'ordering': ['metric_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du tableau de bord')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('dashboard_type', models.CharField(choices=[('entrepreneur', 'Entrepreneur'), ('coach', 'Coach'), ('bailleur', 'Bailleur'), ('admin', 'Administrateur')], max_length=20, verbose_name='Type de tableau de bord')),
                ('layout_config', models.JSONField(default=dict, verbose_name='Configuration du layout')),
                ('widgets', models.JSONField(default=list, verbose_name='Widgets configurés')),
                ('refresh_interval', models.PositiveIntegerField(default=300, verbose_name='Intervalle de rafraîchissement (secondes)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Tableau de bord public')),
                ('is_default', models.BooleanField(default=False, verbose_name='Tableau de bord par défaut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Tableau de bord',
                'verbose_name_plural': 'Tableaux de bord',
                'db_table': 'dashboards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trend_type', models.CharField(choices=[('growth', 'Croissance'), ('decline', 'Déclin'), ('stable', 'Stable'), ('volatile', 'Volatile'), ('seasonal', 'Saisonnier')], max_length=20, verbose_name='Type de tendance')),
                ('trend_strength', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Force de la tendance (%)')),
                ('data_points', models.JSONField(default=list, verbose_name='Points de données')),
                ('trend_line', models.JSONField(default=dict, verbose_name='Ligne de tendance')),
                ('forecast_values', models.JSONField(default=list, verbose_name='Valeurs prédites')),
                ('confidence_interval', models.JSONField(default=dict, verbose_name='Intervalle de confiance')),
                ('analysis_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'analyse")),
                ('period_analyzed', models.CharField(max_length=50, verbose_name='Période analysée')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_analyses', to='entrepreneurs.entrepreneur', verbose_name='Entrepreneur')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_analyses', to='analytics.kpimetric', verbose_name='KPI')),
            ],
            options={
                'verbose_name': 'Analyse de tendance',
                'verbose_name_plural': 'Analyses de tendances',
                'db_table': 'trend_analyses',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='KPIMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valeur mesurée')),
                ('period_start', models.DateField(verbose_name='Début de période')),
                ('period_end', models.DateField(verbose_name='Fin de période')),
                ('measurement_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de mesure')),
                ('data_source', models.CharField(max_length=100, verbose_name='Source de données')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_measurements', to='entrepreneurs.activity', verbose_name='Activité')),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_measurements', to='entrepreneurs.entrepreneur', verbose_name='Entrepreneur')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='analytics.kpimetric', verbose_name='KPI')),
            ],
            options={
                'verbose_name': 'Mesure KPI',
                'verbose_name_plural': 'Mesures KPI',
                'db_table': 'kpi_measurements',
                'ordering': ['-measurement_date'],
                'unique_together': {('kpi', 'entrepreneur', 'activity', 'period_start', 'period_end')},
            },
        ),
    ]
