# Generated by Django 5.0.2 on 2025-09-30 17:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('civility', models.CharField(choices=[('M', 'Monsieur'), ('Mme', 'Madame')], max_length=4, verbose_name='Civilité')),
                ('cni_number', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro CNI doit contenir exactement 13 chiffres.', regex='^[0-9]{13}$')], verbose_name='Numéro CNI')),
                ('address', models.TextField(verbose_name='Adresse complète')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='Numéro WhatsApp')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrepreneur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrepreneur',
                'verbose_name_plural': 'Entrepreneurs',
                'db_table': 'entrepreneurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField(verbose_name='Adresse complète')),
                ('region', models.CharField(max_length=100, verbose_name='Région')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Adresse principale')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='entrepreneurs.entrepreneur')),
            ],
            options={
                'verbose_name': 'Localisation',
                'verbose_name_plural': 'Localisations',
                'db_table': 'locations',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name="Nom de l'activité")),
                ('sector', models.CharField(choices=[('commerce', 'Commerce'), ('service', 'Service'), ('artisanat', 'Artisanat'), ('agriculture', 'Agriculture')], max_length=50, verbose_name="Secteur d'activité")),
                ('description', models.TextField(blank=True, verbose_name="Description de l'activité")),
                ('creation_date', models.DateField(verbose_name='Date de création')),
                ('legal_form', models.CharField(choices=[('Informel', 'Informel'), ('EI', 'Entreprise Individuelle'), ('EURL', 'EURL'), ('SARL', 'SARL'), ('SA', 'SA'), ('GIE', 'GIE'), ('Association', 'Association')], default='Informel', max_length=50, verbose_name='Forme juridique')),
                ('tax_regime', models.CharField(blank=True, choices=[('Non imposable', 'Non imposable'), ('Régime simplifié', 'Régime simplifié'), ('Régime réel', 'Régime réel')], max_length=50, verbose_name='Régime fiscal')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspendue'), ('closed', 'Fermée')], default='active', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='entrepreneurs.entrepreneur')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='entrepreneurs.location')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'db_table': 'activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
