# Generated by Django 5.0.2 on 2025-10-27 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle'), ('quarterly', 'Trimestrielle'), ('yearly', 'Annuelle')], default='monthly', max_length=20, verbose_name='Fréquence'),
        ),
        migrations.AddField(
            model_name='activity',
            name='frequency_day',
            field=models.PositiveIntegerField(blank=True, help_text="Pour les activités mensuelles, le jour du mois où l'activité se déroule", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Jour du mois'),
        ),
    ]
