# Generated by Django 5.0.2 on 2026-03-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs', '0002_activity_frequency_activity_frequency_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='cni_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro CNI'),
        ),
    ]
