# Generated by Django 5.0.2 on 2025-09-30 17:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrepreneurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre du cycle')),
                ('duration_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durée prévue (jours)')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('expected_end_date', models.DateField(verbose_name='Date de fin prévue')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin réelle')),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('delayed', 'En retard')], default='planned', max_length=20, verbose_name='Statut')),
                ('target_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantité cible')),
                ('actual_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantité réalisée')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_cycles', to='entrepreneurs.activity', verbose_name='Activité')),
            ],
            options={
                'verbose_name': 'Cycle de production',
                'verbose_name_plural': 'Cycles de production',
                'db_table': 'production_cycles',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la tâche')),
                ('sequence_order', models.PositiveIntegerField(verbose_name='Ordre de séquence')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('blocked', 'Bloqué')], default='pending', max_length=20, verbose_name='Statut')),
                ('planned_duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée prévue (jours)')),
                ('actual_duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée réelle (jours)')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='Date de début prévue')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin prévue')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='Date de début réelle')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin réelle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_tasks', to='production.productiontask', verbose_name='Dépend de')),
                ('production_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='production.productioncycle', verbose_name='Cycle de production')),
            ],
            options={
                'verbose_name': 'Tâche de production',
                'verbose_name_plural': 'Tâches de production',
                'db_table': 'production_tasks',
                'ordering': ['production_cycle', 'sequence_order'],
                'unique_together': {('production_cycle', 'sequence_order')},
            },
        ),
    ]
