# Generated by Django 5.0.2 on 2025-09-30 17:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrepreneurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('summary', models.TextField(blank=True, verbose_name='Résumé exécutif')),
                ('market_analysis', models.JSONField(default=dict, verbose_name='Analyse de marché')),
                ('offer', models.JSONField(default=dict, verbose_name='Offre et services')),
                ('business_model', models.JSONField(default=dict, verbose_name='Modèle économique')),
                ('financial_projections', models.JSONField(default=dict, verbose_name='Projections financières')),
                ('implementation_plan', models.JSONField(default=dict, verbose_name='Plan de mise en œuvre')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('under_review', 'En cours de révision'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='Statut')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validé')),
                ('validation_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_plans', to='entrepreneurs.activity', verbose_name='Activité')),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_plans', to='entrepreneurs.entrepreneur', verbose_name='Entrepreneur')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_business_plans', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': "Plan d'affaires",
                'verbose_name_plural': "Plans d'affaires",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPlanComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Contenu')),
                ('section', models.CharField(blank=True, max_length=100, verbose_name='Section concernée')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Commentaire interne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_plan_comments', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('business_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='business_plans.businessplan', verbose_name="Plan d'affaires")),
            ],
            options={
                'verbose_name': "Commentaire de plan d'affaires",
                'verbose_name_plural': "Commentaires de plans d'affaires",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPlanTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du template')),
                ('sector', models.CharField(choices=[('commerce', 'Commerce'), ('service', 'Service'), ('artisanat', 'Artisanat'), ('agriculture', 'Agriculture')], max_length=50, verbose_name='Secteur')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('structure', models.JSONField(default=dict, verbose_name='Structure du plan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': "Template de plan d'affaires",
                'verbose_name_plural': "Templates de plans d'affaires",
                'ordering': ['sector', 'name'],
                'unique_together': {('sector', 'version')},
            },
        ),
        migrations.AddField(
            model_name='businessplan',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_plans.businessplantemplate', verbose_name='Template utilisé'),
        ),
        migrations.CreateModel(
            name='BusinessPlanValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('validation_type', models.CharField(choices=[('coach', 'Coach'), ('bailleur', 'Bailleur'), ('admin', 'Administrateur')], max_length=20, verbose_name='Type de validation')),
                ('is_approved', models.BooleanField(verbose_name='Approuvé')),
                ('comments', models.TextField(blank=True, verbose_name='Commentaires')),
                ('score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('business_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='business_plans.businessplan', verbose_name="Plan d'affaires")),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_plan_validations', to=settings.AUTH_USER_MODEL, verbose_name='Validateur')),
            ],
            options={
                'verbose_name': "Validation de plan d'affaires",
                'verbose_name_plural': "Validations de plans d'affaires",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='businessplan',
            unique_together={('entrepreneur', 'activity', 'version')},
        ),
    ]
