# Generated by Django 5.0.2 on 2026-01-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessplan',
            name='pdf_file',
            field=models.FileField(blank=True, help_text="PDF généré du plan d'affaires", null=True, upload_to='business_plans/pdfs/', verbose_name='Fichier PDF'),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PDF généré le'),
        ),
    ]
