# Generated by Django 5.0.2 on 2025-09-30 17:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom du modèle')),
                ('model_type', models.CharField(choices=[('anomaly_detection', "Détection d'anomalies"), ('prediction', 'Prédiction'), ('classification', 'Classification'), ('recommendation', 'Recommandation'), ('optimization', 'Optimisation'), ('nlp', 'Traitement du langage naturel')], max_length=30, verbose_name='Type de modèle')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google AI'), ('azure', 'Azure AI'), ('aws', 'AWS AI'), ('custom', 'Modèle personnalisé')], max_length=20, verbose_name='Fournisseur')),
                ('model_version', models.CharField(max_length=50, verbose_name='Version')),
                ('api_endpoint', models.URLField(blank=True, verbose_name='Endpoint API')),
                ('api_key_name', models.CharField(blank=True, max_length=100, verbose_name='Nom de la clé API')),
                ('parameters', models.JSONField(default=dict, verbose_name='Paramètres du modèle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Précision (%)')),
                ('last_training', models.DateTimeField(blank=True, null=True, verbose_name='Dernier entraînement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Modèle IA',
                'verbose_name_plural': 'Modèles IA',
                'ordering': ['model_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('category', models.CharField(choices=[('financial', 'Financier'), ('operational', 'Opérationnel'), ('compliance', 'Conformité'), ('market', 'Marché'), ('risk', 'Risque'), ('opportunity', 'Opportunité'), ('performance', 'Performance'), ('system', 'Système')], max_length=20, verbose_name='Catégorie')),
                ('description', models.TextField(verbose_name='Description')),
                ('severity_levels', models.JSONField(default=list, verbose_name='Niveaux de sévérité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': "Type d'alerte",
                'verbose_name_plural': "Types d'alertes",
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('financial_health', 'Santé financière'), ('market_trends', 'Tendances du marché'), ('risk_assessment', 'Évaluation des risques'), ('performance_prediction', 'Prédiction de performance'), ('anomaly_detection', "Détection d'anomalies"), ('optimization_suggestion', "Suggestion d'optimisation")], max_length=30, verbose_name="Type d'analyse")),
                ('related_entity_type', models.CharField(blank=True, max_length=50, verbose_name="Type d'entité liée")),
                ('related_entity_id', models.UUIDField(blank=True, null=True, verbose_name="ID de l'entité liée")),
                ('input_data', models.JSONField(default=dict, verbose_name="Données d'entrée")),
                ('analysis_result', models.JSONField(default=dict, verbose_name="Résultats de l'analyse")),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score de confiance (%)')),
                ('processing_time_ms', models.PositiveIntegerField(verbose_name='Temps de traitement (ms)')),
                ('is_successful', models.BooleanField(default=True, verbose_name='Réussi')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur cible')),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts_ai.aimodel', verbose_name='Modèle IA')),
            ],
            options={
                'verbose_name': 'Analyse IA',
                'verbose_name_plural': 'Analyses IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la règle')),
                ('trigger_type', models.CharField(choices=[('threshold', 'Seuil'), ('trend', 'Tendance'), ('anomaly', 'Anomalie'), ('prediction', 'Prédiction'), ('pattern', 'Motif'), ('comparison', 'Comparaison')], max_length=20, verbose_name='Type de déclenchement')),
                ('condition_field', models.CharField(max_length=100, verbose_name='Champ à surveiller')),
                ('condition_operator', models.CharField(choices=[('gt', 'Supérieur à'), ('gte', 'Supérieur ou égal à'), ('lt', 'Inférieur à'), ('lte', 'Inférieur ou égal à'), ('eq', 'Égal à'), ('ne', 'Différent de'), ('contains', 'Contient'), ('in', 'Dans la liste')], max_length=10, verbose_name='Opérateur')),
                ('condition_value', models.JSONField(verbose_name='Valeur de comparaison')),
                ('ai_model', models.CharField(blank=True, max_length=100, verbose_name='Modèle IA utilisé')),
                ('confidence_threshold', models.DecimalField(decimal_places=2, default=80.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Seuil de confiance (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('cooldown_hours', models.PositiveIntegerField(default=24, verbose_name='Délai entre alertes (heures)')),
                ('max_alerts_per_day', models.PositiveIntegerField(default=5, verbose_name='Max alertes par jour')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('alert_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts_ai.alerttype', verbose_name="Type d'alerte")),
            ],
            options={
                'verbose_name': "Règle d'alerte",
                'verbose_name_plural': "Règles d'alertes",
                'ordering': ['alert_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], max_length=20, verbose_name='Niveau de sévérité')),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('acknowledged', 'Reconnue'), ('resolved', 'Résolue'), ('dismissed', 'Ignorée'), ('escalated', 'Escaladée')], default='new', max_length=20, verbose_name='Statut')),
                ('related_entity_type', models.CharField(blank=True, max_length=50, verbose_name="Type d'entité liée")),
                ('related_entity_id', models.UUIDField(blank=True, null=True, verbose_name="ID de l'entité liée")),
                ('context_data', models.JSONField(default=dict, verbose_name='Données de contexte')),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Confiance IA (%)')),
                ('ai_reasoning', models.TextField(blank=True, verbose_name='Raisonnement IA')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Reconnue le')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolue le')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notes de résolution')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='Déclenchée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Reconnue par')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Résolue par')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur cible')),
                ('alert_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alerts_ai.alertrule', verbose_name='Règle déclenchée')),
                ('alert_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts_ai.alerttype', verbose_name="Type d'alerte")),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('push', 'Push'), ('sms', 'SMS'), ('email', 'Email'), ('in_app', "Dans l'application"), ('webhook', 'Webhook')], max_length=20, verbose_name='Type de notification')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('action_url', models.URLField(blank=True, verbose_name="URL d'action")),
                ('action_text', models.CharField(blank=True, max_length=50, verbose_name="Texte de l'action")),
                ('delivery_status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('delivered', 'Livré'), ('failed', 'Échec'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut de livraison')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Livré le')),
                ('delivery_error', models.TextField(blank=True, verbose_name='Erreur de livraison')),
                ('open_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'ouvertures")),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de clics')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts_ai.alert', verbose_name='Alerte associée')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('recommendation_type', models.CharField(choices=[('financial', 'Financier'), ('operational', 'Opérationnel'), ('strategic', 'Stratégique'), ('risk_mitigation', 'Atténuation des risques'), ('growth', 'Croissance'), ('efficiency', 'Efficacité')], max_length=30, verbose_name='Type')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('urgent', 'Urgent')], max_length=20, verbose_name='Priorité')),
                ('action_items', models.JSONField(default=list, verbose_name='Actions à entreprendre')),
                ('expected_impact', models.TextField(verbose_name='Impact attendu')),
                ('implementation_steps', models.JSONField(default=list, verbose_name="Étapes d'implémentation")),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score de confiance (%)')),
                ('is_implemented', models.BooleanField(default=False, verbose_name='Implémenté')),
                ('implemented_at', models.DateTimeField(blank=True, null=True, verbose_name='Implémenté le')),
                ('implementation_notes', models.TextField(blank=True, verbose_name="Notes d'implémentation")),
                ('user_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note utilisateur (1-5)')),
                ('user_feedback', models.TextField(blank=True, verbose_name='Feedback utilisateur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('ai_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts_ai.aianalysis', verbose_name='Analyse IA source')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur cible')),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aianalysis',
            index=models.Index(fields=['target_user', 'analysis_type'], name='alerts_ai_a_target__d3c072_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysis',
            index=models.Index(fields=['ai_model', 'created_at'], name='alerts_ai_a_ai_mode_05fb16_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['target_user', 'status'], name='alerts_ai_a_target__ee16cf_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'severity'], name='alerts_ai_a_alert_t_e2ba54_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['triggered_at'], name='alerts_ai_a_trigger_db767f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'delivery_status'], name='alerts_ai_n_recipie_15d541_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'created_at'], name='alerts_ai_n_notific_45e968_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['target_user', 'recommendation_type'], name='alerts_ai_r_target__3933a1_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['priority', 'is_implemented'], name='alerts_ai_r_priorit_66570a_idx'),
        ),
    ]
