# Generated by Django 5.0.2 on 2026-01-07 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='client_supplier',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fournisseur/Client'),
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='has_invoice',
            field=models.BooleanField(default=False, verbose_name='Facture disponible'),
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numéro de facture/pièce'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='finances.category', verbose_name='Catégorie parente'),
        ),
    ]
