# Generated by Django 5.0.2 on 2025-09-30 17:00

import apps.accounts.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('otp_code', models.CharField(max_length=6, verbose_name='Code OTP')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
            ],
            options={
                'verbose_name': 'Vérification téléphonique',
                'verbose_name_plural': 'Vérifications téléphoniques',
                'db_table': 'phone_verifications',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Adresse email')),
                ('phone', models.CharField(max_length=20, unique=True, validators=[apps.accounts.validators.validate_phone_number], verbose_name='Numéro de téléphone')),
                ('role', models.CharField(choices=[('entrepreneur', 'Entrepreneur'), ('coach', 'Coach'), ('bailleur', 'Bailleur'), ('admin', 'Administrateur')], default='entrepreneur', max_length=20, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Membre du staff')),
                ('language', models.CharField(default='fr', max_length=5, verbose_name='Langue préférée')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'users',
            },
        ),
    ]
