# Generated by Django 5.0.2 on 2025-09-30 17:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrepreneurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization', models.CharField(blank=True, max_length=255, verbose_name='Organisation')),
                ('specialization', models.CharField(choices=[('business_development', "Développement d'entreprise"), ('financial_management', 'Gestion financière'), ('marketing', 'Marketing et vente'), ('operations', 'Opérations et production'), ('legal_compliance', 'Conformité légale'), ('digital_transformation', 'Transformation numérique'), ('sustainability', 'Développement durable'), ('general', 'Accompagnement général')], default='general', max_length=50, verbose_name='Spécialisation')),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name="Années d'expérience")),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('skills', models.JSONField(default=list, verbose_name='Compétences')),
                ('certifications', models.JSONField(default=list, verbose_name='Certifications')),
                ('is_certified', models.BooleanField(default=False, verbose_name='Coach certifié')),
                ('is_active', models.BooleanField(default=True, verbose_name='Coach actif')),
                ('max_entrepreneurs', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name="Nombre max d'entrepreneurs")),
                ('availability_schedule', models.JSONField(default=dict, verbose_name='Planning de disponibilité')),
                ('preferred_contact_method', models.CharField(choices=[('phone', 'Téléphone'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='whatsapp', max_length=20, verbose_name='Méthode de contact préférée')),
                ('success_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de réussite (%)')),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note moyenne')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Coach',
                'verbose_name_plural': 'Coaches',
                'db_table': 'coaches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('paused', 'En pause')], default='active', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('objectives', models.JSONField(default=list, verbose_name='Objectifs')),
                ('progress_notes', models.TextField(blank=True, verbose_name='Notes de progression')),
                ('initial_assessment', models.JSONField(default=dict, verbose_name='Évaluation initiale')),
                ('final_assessment', models.JSONField(default=dict, verbose_name='Évaluation finale')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='coaches.coach', verbose_name='Coach')),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_assignments', to='entrepreneurs.entrepreneur', verbose_name='Entrepreneur')),
            ],
            options={
                'verbose_name': 'Assignation coach',
                'verbose_name_plural': 'Assignations coaches',
                'db_table': 'coach_assignments',
                'ordering': ['-created_at'],
                'unique_together': {('coach', 'entrepreneur')},
            },
        ),
        migrations.CreateModel(
            name='CoachingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('initial', 'Session initiale'), ('follow_up', 'Suivi'), ('milestone', 'Étape importante'), ('final', 'Session finale'), ('emergency', 'Urgence')], max_length=20, verbose_name='Type de session')),
                ('status', models.CharField(choices=[('scheduled', 'Planifiée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('no_show', 'Absence')], default='scheduled', max_length=20, verbose_name='Statut')),
                ('scheduled_date', models.DateTimeField(verbose_name='Date planifiée')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Durée (minutes)')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Début réel')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fin réelle')),
                ('agenda', models.TextField(blank=True, verbose_name='Ordre du jour')),
                ('notes', models.TextField(blank=True, verbose_name='Notes de session')),
                ('action_items', models.JSONField(default=list, verbose_name='Actions à suivre')),
                ('entrepreneur_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note entrepreneur (1-5)')),
                ('coach_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note coach (1-5)')),
                ('feedback', models.TextField(blank=True, verbose_name="Retour d'expérience")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='coaches.coachassignment', verbose_name='Assignation')),
            ],
            options={
                'verbose_name': 'Session de coaching',
                'verbose_name_plural': 'Sessions de coaching',
                'db_table': 'coaching_sessions',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
