# Generated by Django 5.0.2 on 2026-01-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingsession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Planifiée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('no_show', 'Absence'), ('evaluation_completed', "Évaluation terminée par l'entrepreneur")], default='scheduled', max_length=20, verbose_name='Statut'),
        ),
    ]
