# Generated by Django 5.0.2 on 2025-09-30 17:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_plans', '0001_initial'),
        ('entrepreneurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bailleur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=255, verbose_name="Nom de l'organisation")),
                ('organization_type', models.CharField(choices=[('ong', 'ONG'), ('incubateur', 'Incubateur'), ('banque', 'Banque'), ('microfinance', 'Institution de microfinance'), ('fonds', "Fonds d'investissement"), ('gouvernement', 'Institution gouvernementale'), ('international', 'Organisation internationale'), ('prive', 'Secteur privé')], max_length=50, verbose_name="Type d'organisation")),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Personne de contact')),
                ('contact_position', models.CharField(blank=True, max_length=100, verbose_name='Poste du contact')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('sectors_supported', models.JSONField(default=list, verbose_name='Secteurs soutenus')),
                ('regions_covered', models.JSONField(default=list, verbose_name='Régions couvertes')),
                ('funding_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Capacité de financement (FCFA)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Bailleur actif')),
                ('total_funding_provided', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total financé (FCFA)')),
                ('entrepreneurs_supported', models.PositiveIntegerField(default=0, verbose_name="Nombre d'entrepreneurs soutenus")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bailleur', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Bailleur',
                'verbose_name_plural': 'Bailleurs',
                'db_table': 'bailleurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundingProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=255, verbose_name='Nom du programme')),
                ('description', models.TextField(verbose_name='Description')),
                ('funding_type', models.CharField(choices=[('grant', 'Subvention'), ('loan', 'Prêt'), ('equity', 'Prise de participation'), ('hybrid', 'Financement hybride'), ('technical_assistance', 'Assistance technique')], max_length=50, verbose_name='Type de financement')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant minimum (FCFA)')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant maximum (FCFA)')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('application_deadline', models.DateField(verbose_name='Date limite de candidature')),
                ('target_sectors', models.JSONField(default=list, verbose_name='Secteurs cibles')),
                ('target_regions', models.JSONField(default=list, verbose_name='Régions cibles')),
                ('eligibility_criteria', models.JSONField(default=list, verbose_name="Critères d'éligibilité")),
                ('required_documents', models.JSONField(default=list, verbose_name='Documents requis')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('paused', 'En pause'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut')),
                ('total_applications', models.PositiveIntegerField(default=0, verbose_name='Total candidatures')),
                ('approved_applications', models.PositiveIntegerField(default=0, verbose_name='Candidatures approuvées')),
                ('total_funding_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total financé (FCFA)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_programs', to='bailleurs.bailleur', verbose_name='Bailleur')),
            ],
            options={
                'verbose_name': 'Programme de financement',
                'verbose_name_plural': 'Programmes de financement',
                'db_table': 'funding_programs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundingApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant demandé (FCFA)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumise'), ('under_review', "En cours d'examen"), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('withdrawn', 'Retirée')], default='draft', max_length=20, verbose_name='Statut')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'examen")),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant approuvé (FCFA)')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Raison du rejet')),
                ('project_description', models.TextField(verbose_name='Description du projet')),
                ('expected_impact', models.TextField(verbose_name='Impact attendu')),
                ('implementation_timeline', models.JSONField(default=dict, verbose_name='Calendrier de mise en œuvre')),
                ('supporting_documents', models.JSONField(default=list, verbose_name='Documents de soutien')),
                ('evaluation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Score d'évaluation")),
                ('evaluation_notes', models.TextField(blank=True, verbose_name="Notes d'évaluation")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_applications', to='entrepreneurs.activity', verbose_name='Activité')),
                ('business_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_plans.businessplan', verbose_name="Plan d'affaires")),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_applications', to='entrepreneurs.entrepreneur', verbose_name='Entrepreneur')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='bailleurs.fundingprogram', verbose_name='Programme')),
            ],
            options={
                'verbose_name': 'Candidature au financement',
                'verbose_name_plural': 'Candidatures au financement',
                'db_table': 'funding_applications',
                'ordering': ['-created_at'],
                'unique_together': {('entrepreneur', 'activity', 'program')},
            },
        ),
    ]
